package Domain;
// Generated Nov 5, 2017 11:17:51 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Donhang generated by hbm2java
 */
public class Donhang  implements java.io.Serializable {


     private Integer maDh;
     private Nhanvien nhanvien;
     private String tenKh;
     private String sdt;
     private String diaChi;
     private Date tggiaoHang;
     private Set<Chitietdonhang> chitietdonhangs = new HashSet<Chitietdonhang>(0);
     private Hoadon hoadon;

    public Donhang() {
    }

    public Donhang(Nhanvien nhanvien, String tenKh, String sdt, String diaChi, Date tggiaoHang, Set<Chitietdonhang> chitietdonhangs, Hoadon hoadon) {
       this.nhanvien = nhanvien;
       this.tenKh = tenKh;
       this.sdt = sdt;
       this.diaChi = diaChi;
       this.tggiaoHang = tggiaoHang;
       this.chitietdonhangs = chitietdonhangs;
       this.hoadon = hoadon;
    }
   
    public Integer getMaDh() {
        return this.maDh;
    }
    
    public void setMaDh(Integer maDh) {
        this.maDh = maDh;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public String getTenKh() {
        return this.tenKh;
    }
    
    public void setTenKh(String tenKh) {
        this.tenKh = tenKh;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public Date getTggiaoHang() {
        return this.tggiaoHang;
    }
    
    public void setTggiaoHang(Date tggiaoHang) {
        this.tggiaoHang = tggiaoHang;
    }
    public Set<Chitietdonhang> getChitietdonhangs() {
        return this.chitietdonhangs;
    }
    
    public void setChitietdonhangs(Set<Chitietdonhang> chitietdonhangs) {
        this.chitietdonhangs = chitietdonhangs;
    }
    public Hoadon getHoadon() {
        return this.hoadon;
    }
    
    public void setHoadon(Hoadon hoadon) {
        this.hoadon = hoadon;
    }




}


