package Domain;
// Generated Nov 9, 2017 11:16:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loaisp generated by hbm2java
 */
public class Loaisp  implements java.io.Serializable {


     private Integer id;
     private String tenLoaiSp;
     private Set<Sanpham> sanphams = new HashSet<Sanpham>(0);

    public Loaisp() {
    }

    public Loaisp(String tenLoaiSp, Set<Sanpham> sanphams) {
       this.tenLoaiSp = tenLoaiSp;
       this.sanphams = sanphams;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTenLoaiSp() {
        return this.tenLoaiSp;
    }
    
    public void setTenLoaiSp(String tenLoaiSp) {
        this.tenLoaiSp = tenLoaiSp;
    }
    public Set<Sanpham> getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set<Sanpham> sanphams) {
        this.sanphams = sanphams;
    }




}


