package Domain;
// Generated Nov 11, 2017 4:10:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String password;
     private Integer trangThai;
     private String phanQuyen;
     private Set<Comment> comments = new HashSet<Comment>(0);

    public Taikhoan() {
    }

	
    public Taikhoan(String userName) {
        this.userName = userName;
    }
    public Taikhoan(String userName, String password, Integer trangThai, String phanQuyen, Set<Comment> comments) {
       this.userName = userName;
       this.password = password;
       this.trangThai = trangThai;
       this.phanQuyen = phanQuyen;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }
    public String getPhanQuyen() {
        return this.phanQuyen;
    }
    
    public void setPhanQuyen(String phanQuyen) {
        this.phanQuyen = phanQuyen;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }




}


